{% set name = "motor" %}
{% set version = "2.0.0" %}
{% set sha256 = "d035c09ab422bc50bf3efb134f7405694cae76268545bd21e14fb22e2638f84e" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 1001
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - aiohttp
    - tornado >=4.0
    - pymongo >=3.7
    - python =2.7|>=3.5.2
  run:
    - pymongo >=3.7
    - aiohttp
    - tornado >=4.0
    - python =2.7|>=3.5.2

test:
  imports:
    - motor
    - motor.aiohttp
    - motor.frameworks
    - motor.frameworks.asyncio
    - motor.frameworks.tornado

about:
  home: https://github.com/mongodb/motor/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Non-blocking MongoDB driver for Tornado or asyncio
  doc_url: https://motor.readthedocs.io
  dev_url: https://github.com/mongodb/motor

extra:
  recipe-maintainers:
    - hodgsonw
