{% set name = "motor" %}
{% set version = "3.2.0" %}
{% set sha256 = "4fb1e8502260f853554f24115421584e83904a6debb577354d33e9711ee99008" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - aiohttp
    - tornado >=6.0
    - pymongo >=4.1,<5
    - python >=3.7
  run:
    - aiohttp
    - tornado >=6.0
    - pymongo >=4.4,<5
    - python >=3.7

test:
  imports:
    - motor
    - motor.aiohttp
    - motor.frameworks
    - motor.frameworks.asyncio
    - motor.frameworks.tornado

about:
  home: https://github.com/mongodb/motor/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Non-blocking MongoDB driver for Tornado or asyncio
  doc_url: https://motor.readthedocs.io
  dev_url: https://github.com/mongodb/motor

extra:
  recipe-maintainers:
    - hodgsonw
    - ShaneHarvey
    - blink1073
    - hodgsonw
