{% set name = "motor" %}
{% set version = "3.6.1" %}
{% set sha256 = "ee2b18386292f9ceb3cc8279a4cd34e4c641c5ac8de3500c30374081c76a9d03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-cache-dir --no-build-isolation

requirements:
  host:
    - pip
    - aiohttp
    - hatchling >=1.24
    - hatch-requirements-txt >=0.4.1
    - tornado >=6.0
    - pymongo >=4.9,<4.10
    - python {{ python_min }}
  run:
    - aiohttp
    - tornado >=6.0
    - pymongo >=4.9,<4.10
    - python >={{ python_min }}

test:
  source_files:
    - .
  files:
    - run_the_tests.sh
  requires:
    - mongodb
    - setuptools
    - pytest
    - mockupdb
    - pymongo >=4.9,<4.10
    - pip
    - python {{ python_min }}
  imports:
    - motor
    - motor.aiohttp
    - motor.frameworks
    - motor.frameworks.asyncio
    - motor.frameworks.tornado
  commands:
    - bash run_the_tests.sh
    - pip check

about:
  home: https://github.com/mongodb/motor/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Non-blocking MongoDB driver for Tornado or asyncio
  doc_url: https://motor.readthedocs.io
  dev_url: https://github.com/mongodb/motor

extra:
  recipe-maintainers:
    - hodgsonw
    - ShaneHarvey
    - blink1073
    - hodgsonw
