{% set name = "motor" %}
{% set version = "3.4.0" %}
{% set sha256 = "c89b4e4eb2e711345e91c7c9b122cb68cce0e5e869ed0387dd0acb10775e3131" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - aiohttp
    - tornado >=6.0
    - pymongo >=4.5,<5
    - python >=3.7
  run:
    - aiohttp
    - tornado >=6.0
    - pymongo >=4.5,<5
    - python >=3.7

test:
  source_files:
    - .
  files:
    - run_the_tests.sh
  requires:
    - mongodb
    - setuptools
    - pytest
    - mockupdb
    - pymongo >=4.5,<5
    - pip
  imports:
    - motor
    - motor.aiohttp
    - motor.frameworks
    - motor.frameworks.asyncio
    - motor.frameworks.tornado
  commands:
    - bash run_the_tests.sh
    - pip check

about:
  home: https://github.com/mongodb/motor/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Non-blocking MongoDB driver for Tornado or asyncio
  doc_url: https://motor.readthedocs.io
  dev_url: https://github.com/mongodb/motor

extra:
  recipe-maintainers:
    - hodgsonw
    - ShaneHarvey
    - blink1073
    - hodgsonw
