{% set name = "motor" %}
{% set version = "2.3.0" %}
{% set sha256 = "f1692b760d834707e3477996ce8d407af8cd61c1a2abedbf81c22ef14675e61a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - aiohttp
    - tornado >=5.0
    - pymongo >=3.11,<4
    - python >=3.5.2
  run:
    - aiohttp
    - tornado >=5.0
    - pymongo >=3.11,<4
    - python >=3.5.2

test:
  imports:
    - motor
    - motor.aiohttp
    - motor.frameworks
    - motor.frameworks.asyncio
    - motor.frameworks.tornado

about:
  home: https://github.com/mongodb/motor/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Non-blocking MongoDB driver for Tornado or asyncio
  doc_url: https://motor.readthedocs.io
  dev_url: https://github.com/mongodb/motor

extra:
  recipe-maintainers:
    - hodgsonw
    - ShaneHarvey
    - blink1073
